### ISSUE TITLE
Allow re-use of bars and/or nesting multiple bars

### ISSUE THREAD

**Issue by jkorinth** [mrlazy1708/tqdm#14]
Nested tqdm iterators like this
```rs
for &i in tqdm(a.iter()) {
  for &j in tqdm(b.iter()) {
    ...
  }
}
```
currently produce a new bar and a newline on each iteration of the outer loop. It would be nice to be able to re-use the inner bar (reset count and state), e.g.,
```rs
let mut inner_bar = tqdm::bar();
for &i in tqdm(a.iter()) {
  for &j in inner_bar.reset(b.iter()) {
    ...
  }
}
```
Another approach may be to have a multibar environment that automatically keeps track of the named bars and re-uses them, e.g.,
```rs
let mut mb = tqdm::Multibar::new();
for &i in tqdm(a.iter()).desc(Some("outer")) {
  for &j in tqdm(b.iter()).desc(Some("inner")) {
    ...
  }
}
```

**Comment by mrlazy1708** [comment]
Hi @jkorinth, I got what you mean and thanks for bringing this up. The problem here seems to be the behavior of line breaking after termination. Currently I have line breaks anyway, so the outer bar would move forward every iteration.

Regarding the fixes you mentioned, I think both are doable for this purpose, despite the feeling that both are a little bit anti-Rusty. I checked out py tqdm and found there's a `leave` argument in its param list. I guess this could be the easiest way to go. In py it looks like:

```python
for a in tqdm([1, 2, 3, 4, 5, 6, 7]):
    for b in tqdm([1, 2, 3], leave=False):
        for c in tqdm([1, 2, 3], leave=False):

            from time import sleep
            sleep(0.1)

```

If that also works in your situation I'll add `leave` to the builder

**Comment by mrlazy1708** [comment]
Does 1aa14ae5b1a14cbff3c2fa38947cf20532a0152d fix your case? @jkorinth

**Comment by mrlazy1708** [comment]
While another bug I noticed is that after switching to hash map 97dab2867a1a2a97d50bf1382e6fe3ed49de0372, the order of bars is messed up - will fix it soon

**Comment by jkorinth** [comment]
@mrlazy1708 Yes, that is looking very good, thanks!
